n = input('Digite algo')
print(n, 'é Alnum?')
print(n.isalnum())
print(n, 'é Alpha?')
print(n.isalpha())
print(n, 'é Decimal?')
print(n.isdecimal())
print(n, 'é Digit?')
print(n.isdigit())
print(n, 'é Minusculo?')
print(n.islower())
print(n, 'é Numerico?')
print(n.isnumeric())
print(n, 'é identifier?')
print(n.isidentifier())
print(n, 'é printable?')
print(n.isprintable())
print(n, 'é um espaço?')
print(n.isspace())
print(n, 'é um titulo?')
print(n.istitle())
print(n, 'é Maiusculo?')
print(n.isupper())

