n1 = int(input('Digite um número para saber seu dobro,triplo e a raiz quadrada'))
n2 = int(n1*2)
n3 = int(n1 ** 2)
n4 = int(n1*3)
print('O dobro é{} A raiz quadrada é{}O triplo é{}'.format(n2, n3, n4))
